apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: janeonthegame
  
  source:
    repoURL: https://github.com/yourusername/janeonthegame-k8s.git
    targetRevision: develop
    path: charts/frontend
    helm:
      valueFiles:
        - ../../environments/staging/frontend-values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: janeonthegame-staging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
