apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
  TZ: "Africa/Nairobi"
  LOG_LEVEL: "info"
  
  # Database Configuration
  DATABASE_URL: "postgresql://username:password@your-database-host:5432/janeonthegame"
  
  # Authentication
  JWT_SECRET: "change-this-to-a-very-secure-random-string-min-32-chars"
  
  # Paystack Payment Gateway
  PAYSTACK_SECRET_KEY: "sk_live_your_paystack_secret_key_here"
  PAYSTACK_PUBLIC_KEY: "pk_live_your_paystack_public_key_here"
  
  # Football Data API (Optional)
  FOOTBALL_DATA_ORG_KEY: "your_football_data_api_key_or_remove_this_line"
  
  # Africa's Talking SMS (Optional)
  AFRICASTALKING_API_KEY: "your_africastalking_api_key_or_remove"
  AFRICASTALKING_USERNAME: "your_africastalking_username_or_remove"
  
  # Email SMTP Configuration (Optional)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASS: "your-app-specific-password"
  
  # CORS Configuration (Optional)
  CORS_ORIGIN: "https://janeonthegame.com,https://www.janeonthegame.com"
