apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: default
type: Opaque
stringData:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "3000"
  
  # API Configuration
  NEXT_PUBLIC_API_URL: "https://api.janeonthegame.com/graphql"
  
  # Optional: Analytics, Ads, etc.
  # NEXT_PUBLIC_GA_ID: "G-XXXXXXXXXX"
  # NEXT_PUBLIC_ADSENSE_ID: "ca-pub-XXXXXXXXXX"
